# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuedate', models.DateField()),
                ('cftype', models.CharField(choices=[('Equity', 'Equity'), ('Proceeds', 'Proceeds')], max_length=200)),
                ('cashflows', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=15)),
                ('fund', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cashflows',
            name='did',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Deal'),
        ),
    ]
